theme: jekyll-theme-cayman

# Site Settings
title: "Michael Grogan"
name: "Michael Grogan"
description: "Data Science Consultant

Expertise in Time Series Analysis, Statistics, Bayesian Modelling, and Machine Learning with TensorFlow"
